version: "3.9"

services:
  receiver:
    build: projektarbete-receiver
    ports:
      - "8080:8080"
    depends_on:
      - artemis
      - db
  sender:
    build: projektarbete-sender
    ports:
      - "8081:8080"
    depends_on:
      - artemis
      - db
  artemis:
    # arm - image: amusarra/apache-artemis:2.17.0
    # x64 - image: vromero/activemq-artemis
    image: vromero/activemq-artemis
    ports:
      - "8161:8161"
      - "61616:61616"
    environment:
      ARTEMIS_USERNAME: "artemis"
      ARTEMIS_PASSWORD: "simetraehcapa"
  db:
    image: mariadb:10.5
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: mypass
      MYSQL_DATABASE: chat
    volumes:
      - db_data:/var/lib/mysql/data
volumes:
  db_data: {}